import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import jsxA11y from "eslint-plugin-jsx-a11y";
import simpleImportSort from "eslint-plugin-simple-import-sort";
import unusedImports from "eslint-plugin-unused-imports";

import pulse from "./eslint-rules/no-unguarded-server-action.js";

// Re-declared by name: flat config forbids re-registering a plugin like
// jsx-a11y directly.
const a11yRules = Object.fromEntries(
  Object.keys(jsxA11y.flatConfigs.recommended.rules ?? {}).map((rule) => [rule, "error"])
);

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  {
    rules: {
      ...a11yRules,

      // next/link renders a valid anchor; the rule cannot see through it.
      "jsx-a11y/anchor-is-valid": "off",

      // A scrollable region must be focusable to be keyboard-operable, which
      // this rule does not account for.
      "jsx-a11y/no-noninteractive-tabindex": [
        "error",
        { tags: [], roles: ["tabpanel", "group"], allowExpressionValues: true },
      ],

      // Deprecated upstream, and demands both nesting AND htmlFor, so correct
      // markup fails it. `label-has-associated-control` replaces it.
      "jsx-a11y/label-has-for": "off",
      "jsx-a11y/label-has-associated-control": ["error", { assert: "either" }],

      // Cannot see a label associated by id across elements, so it fires on
      // every correctly labelled input.
      "jsx-a11y/control-has-associated-label": "off",
    },
  },

  {
    plugins: { "simple-import-sort": simpleImportSort, "unused-imports": unusedImports },
    rules: {
      "simple-import-sort/imports": "error",
      "simple-import-sort/exports": "error",
      "unused-imports/no-unused-imports": "error",
      "unused-imports/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },

  {
    // Playwright's fixture API takes a callback named `use`, which the React
    // hooks rule mistakes for a hook call. Nothing in e2e/ is React.
    files: ["e2e/**/*.ts"],
    rules: { "react-hooks/rules-of-hooks": "off" },
  },

  {
    files: ["app/actions/**/*.ts"],
    plugins: { pulse },
    rules: { "pulse/no-unguarded-server-action": "error" },
  },

  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `prisma generate`; not ours to lint.
    "app/generated/**",
    "playwright-report/**",
    "test-results/**",
    // Claude Design canvas export (gitignored) — generated markup nobody
    // edits, so don't lint it.
    "UI ref/**",
  ]),
]);

export default eslintConfig;
